export const POKEMON_TYPES = [
  { label: "Acero", value: "steel" },
  { label: "Agua", value: "water" },
  { label: "Bicho", value: "bug" },
  { label: "Dragón", value: "dragon" },
  { label: "Eléctrico", value: "electric" },
  { label: "Fantasma", value: "ghost" },
  { label: "Fuego", value: "fire" },
  { label: "Hada", value: "fairy" },
  { label: "Hielo", value: "ice" },
  { label: "Lucha", value: "fighting" },
  { label: "Normal", value: "normal" },
  { label: "Planta", value: "grass" },
  { label: "Psíquico", value: "psychic" },
  { label: "Roca", value: "rock" },
  { label: "Siniestro", value: "dark" },
  { label: "Tierra", value: "ground" },
  { label: "Veneno", value: "poison" },
  { label: "Volador", value: "flying" },
];

export const TYPE_COLORS = {
  normal: "#9FA19F",
  fire: "#E62829",
  water: "#2980EF",
  electric: "#FAC000",
  grass: "#3FA129",
  ice: "#3FD8FF",
  fighting: "#FF8000",
  poison: "#8F41CB",
  ground: "#915121",
  flying: "#81B9EF",
  psychic: "#EF4179",
  bug: "#91A119",
  rock: "#AFA981",
  ghost: "#704170",
  dragon: "#5061E1",
  dark: "#50413F",
  steel: "#60A1B8",
  fairy: "#EF71EF",
};
