export const POKEMON_TYPES = [
  { label: "Acero", value: "steel" },
  { label: "Agua", value: "water" },
  { label: "Bicho", value: "bug" },
  { label: "Dragón", value: "dragon" },
  { label: "Eléctrico", value: "electric" },
  { label: "Fantasma", value: "ghost" },
  { label: "Fuego", value: "fire" },
  { label: "Hada", value: "fairy" },
  { label: "Hielo", value: "ice" },
  { label: "Lucha", value: "fighting" },
  { label: "Normal", value: "normal" },
  { label: "Planta", value: "grass" },
  { label: "Psíquico", value: "psychic" },
  { label: "Roca", value: "rock" },
  { label: "Siniestro", value: "dark" },
  { label: "Tierra", value: "ground" },
  { label: "Veneno", value: "poison" },
  { label: "Volador", value: "flying" },
];
